# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-24 21:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('km', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('zip_code', models.CharField(max_length=5)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='km.Province')),
            ],
        ),
    ]
